#!/bin/sh

domain=$1

#定义证书文件路径
cert_path="/etc/letsencrypt/live/$domain/fullchain.pem"
#定义证书需要更新的最小剩余天数
min_days_remaining=7
#获取证书的剩余有效天数
end_date=$(openssl x509 -enddate -noout -in $cert_path | cut -d "=" -f 2)
end_timestamp=$(date -d "$end_date" +%s)
current_timestamp=$(date +%s)
days_remaining=$((($end_timestamp - $current_timestamp) / 86400))

# 检查剩余天数是否小于最小值
if [ "$days_remaining" -lt "$min_days_remaining" ]; then
    echo "证书还剩 $days_remaining 天，开始更新证书。"
    # 更新证书
    docker stop hk-nginx
    certbot renew

    # 启动 Docker 容器
    docker start hk-nginx
    echo "证书更新完成。"
else
    echo "证书还剩 $days_remaining 天，无需更新。"
fi